# application: ownyourresponses
# version: 1
runtime: python27
threadsafe: yes
api_version: 1

builtins:
- remote_api: on
- appstats: on

libraries:
- name: lxml
  version: latest
- name: ssl
  version: latest

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /cron/poll
  script: app.application
  login: admin
  secure: always

skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?(debian|docs?|examples?|l|pydocs?|python3|ref|samples?|tests?)/.*
