# https://cloud.google.com/appengine/docs/standard/python3/config/appref

# application: ownyourresponses
runtime: python39

# https://cloud.google.com/appengine/docs/standard/python3/runtime#entrypoint_best_practices
# https://docs.gunicorn.org/en/latest/settings.html#timeout
entrypoint: gunicorn --workers 1 --threads 3 --timeout 60 -b :$PORT app:app

inbound_services:
- warmup

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

# dynamic
- url: .*
  script: auto
  secure: always
  # login: admin
